import { absoluteSiteUrl } from "./site.ts";

/**
 * Official unique public HTML marketing/docs pages generated by this
 * Next.js export. Each path is an App Router page in this repo and was
 * observed as HTTP 200 on https://autogive.app (apex, 2026-08-22).
 *
 * Not listed (do not invent; not this export's HTML):
 * - /brand — linked in the footer, live 404
 * - /login, /admin — parked shells in this repo; noindex, not marketing pages
 * - /portfolio-signals/ and /impact-relay/ — first-party 200s on the apex via
 *   workers/suite-routes.ts, but owned by other product repos (out of scope)
 * - Portfolio Signals workspace, members, donor-impact, finance-impact,
 *   import-review — auth, dashboard, or PII-adjacent (see robots disallows)
 */
export const OFFICIAL_PUBLIC_HTML_PAGES = [
  { path: "/", changeFrequency: "weekly", priority: 1 },
  { path: "/legal", changeFrequency: "monthly", priority: 0.6 },
  { path: "/legal/privacy", changeFrequency: "monthly", priority: 0.6 },
  { path: "/legal/terms", changeFrequency: "monthly", priority: 0.6 },
] as const;

/**
 * Auth, admin, workspace, and PII-adjacent paths this host serves.
 * Observed in app/ routes and workers/suite-routes.ts; verified on the apex.
 */
export const ROBOTS_DISALLOW_PATHS = [
  "/login",
  "/admin",
  "/workspace",
  "/portfolio-signals/workspace",
  "/portfolio-signals/members",
  "/portfolio-signals/donor-impact",
  "/portfolio-signals/finance-impact",
  "/portfolio-signals/import-review",
] as const;

export const SITEMAP_LAST_MODIFIED = new Date("2026-08-08");

export function officialPublicSitemapUrls(): string[] {
  return OFFICIAL_PUBLIC_HTML_PAGES.map((page) => absoluteSiteUrl(page.path));
}

export function officialPublicSitemapEntries() {
  return OFFICIAL_PUBLIC_HTML_PAGES.map((page) => ({
    url: absoluteSiteUrl(page.path),
    lastModified: SITEMAP_LAST_MODIFIED,
    changeFrequency: page.changeFrequency,
    priority: page.priority,
  }));
}

export function robotsSitemapUrl(): string {
  return absoluteSiteUrl("/sitemap.xml");
}
